#!/usr/bin/env bash
# ============================================================
# ALFA Reports — Interactive .env configurator for Hostinger VPS
# Run: bash scripts/configure-env.sh
# ============================================================
set -euo pipefail

ENV_FILE=".env"

echo "============================================================"
echo "  ALFA Reports — .env Configurator"
echo "============================================================"
echo ""
echo "This script will ask you for 4 values and write the .env file."
echo "Press Ctrl+C at any time to abort."
echo ""

# Backup existing .env if present
if [ -f "$ENV_FILE" ]; then
    cp "$ENV_FILE" "${ENV_FILE}.bak.$(date +%s)"
    echo "(Backed up existing .env)"
fi

# 1. META_API_TOKEN
echo "─── 1/4 ─── META_API Token ───"
echo "Get it from: https://app.metaapi.cloud/api-token"
echo "  → Create token → scopes: Account provisioning + Trading"
echo ""
read -p "Paste your MetaAPI token: " META_TOKEN
echo ""

# 2. TELEGRAM_BOT_TOKEN
echo "─── 2/4 ─── Telegram Bot Token ───"
echo "Get it from @BotFather in Telegram:"
echo "  /newbot → choose name + username → token is provided"
echo "Format: 1234567890:AAH..."
echo ""
read -p "Paste your Telegram bot token: " TG_TOKEN
echo ""

# 3. ADMIN_TELEGRAM_ID
echo "─── 3/4 ─── Your Telegram User ID ───"
echo "Get it from @userinfobot in Telegram:"
echo "  Send /start → it replies with your numeric ID"
echo ""
read -p "Paste your Telegram user ID (numbers only): " TG_ID
echo ""

# 4. VPS IP or domain
echo "─── 4/4 ─── VPS IP or Domain ───"
echo "Examples:"
echo "  185.123.45.67    (VPS IP, port 3000)"
echo "  bot.scalper.com  (after Traefik setup, HTTPS)"
echo ""
read -p "Enter your VPS IP or domain: " VPS_HOST
echo ""

# Generate random ADMIN_API_TOKEN
ADMIN_TOKEN=$(openssl rand -base64 32 | tr -d '/+=' | head -c 48)
if [ -z "$ADMIN_TOKEN" ]; then
    # Fallback if openssl not available
    ADMIN_TOKEN=$(head -c 48 /dev/urandom | xxd -p | head -c 48)
fi

# Determine ALFA_APP_BASE_URL
if [[ "$VPS_HOST" == *.*.*.* ]] || [[ "$VPS_HOST" =~ ^[0-9]+\.[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
    BASE_URL="http://${VPS_HOST}:3000"
elif [[ "$VPS_HOST" == *.com ]] || [[ "$VPS_HOST" == *.net ]] || [[ "$VPS_HOST" == *.org ]]; then
    BASE_URL="https://${VPS_HOST}"
else
    BASE_URL="http://${VPS_HOST}:3000"
fi

# Write .env
cat > "$ENV_FILE" <<EOF
# ============================================================
# ALFA Reports — Production .env (Hostinger VPS)
# Generated by: scripts/configure-env.sh
# Date: $(date -u '+%Y-%m-%d %H:%M:%S UTC')
# ============================================================

# --- Database ---
DATABASE_URL=file:/app/db/custom.db

# --- MetaAPI Cloud ---
META_API_TOKEN=${META_TOKEN}
META_API_PROVISIONING_DOMAIN=mt-provisioning.cloud-trail.com
META_API_CLIENT_REGION=new-york

# --- Telegram bot ---
TELEGRAM_BOT_TOKEN=${TG_TOKEN}
ADMIN_TELEGRAM_ID=${TG_ID}

# --- Shared admin secret (auto-generated) ---
ADMIN_API_TOKEN=${ADMIN_TOKEN}

# --- App base URL ---
ALFA_APP_BASE_URL=${BASE_URL}
EOF

# Tight permissions (contains secrets)
chmod 600 "$ENV_FILE"

echo "============================================================"
echo "  .env file written successfully"
echo "============================================================"
echo ""
echo "File: $ENV_FILE (permissions: 600)"
echo ""
echo "Values saved:"
echo "  META_API_TOKEN:      ${META_TOKEN:0:20}..."
echo "  TELEGRAM_BOT_TOKEN:  ${TG_TOKEN:0:15}..."
echo "  ADMIN_TELEGRAM_ID:   $TG_ID"
echo "  ADMIN_API_TOKEN:     ${ADMIN_TOKEN:0:20}... (auto-generated)"
echo "  ALFA_APP_BASE_URL:   $BASE_URL"
echo ""
echo "Next steps:"
echo "  1. Verify:  cat .env"
echo "  2. Build:   docker compose up -d --build"
echo "  3. Logs:    docker logs -f alfa-reports"
echo "  4. Health:  curl http://localhost:3000/api/system/mode"
echo ""
echo "To regenerate ADMIN_API_TOKEN later, re-run this script."
